apiVersion: apps/v1
kind: Deployment
metadata:
  name: skycrypt-javelin
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: skycrypt-javelin
  template:
    metadata:
      labels:
        app: skycrypt-javelin
    spec:
      containers:
      - image: warpwing/skycrypt-javelin:latest
        name: skycrypt-javelin
        ports:
        - containerPort: 32464
        targetport: 32646
