kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: skycrypt-javelin
spec: 
  maxReplicas: 5
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: app/v1 
    kind: Deployment 
    name: skycrypt-javelin
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 70
