apiVersion: apps/v1
kind: Deployment
metadata:
  name: skycrypt-javelin
  labels: 
    app: skycrypt-javelin
spec:
  selector:
    matchLabels:
      app: skycrypt-javelin
  template:
    metadata:
      labels:
        app: skycrypt-javelin
    spec:
      containers:
      - image: warpwing/skycrypt-javelin:latest
        name: skycrypt-javelin
        ports:
        - containerPort: 32464
        targetport: 32464
        resources: 
          requests: 
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
