apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongobongo
spec:
  selector:
    matchLabels:
      role: mongobongo
      environment: test
  serviceName: "mongobongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongobongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongobongo
        image: mongo
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--smallfiles"
          - "--noprealloc"
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongobongo,environment=test" 
          - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: "SC-Default"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 60Gi